export const APP_NAME = 'Hiring Platform';
export const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'https://content-connection-production-f00a.up.railway.app/api/v1';

export const JOB_TYPES = ['full-time', 'part-time', 'contract', 'remote', 'internship'] as const;

export const APPLICATION_STATUSES = [
  'applied', 'in_review', 'shortlisted', 'interview', 'offer', 'hired', 'rejected',
] as const;

export const APPLICATION_STATUS_LABELS: Record<string, string> = {
  applied: 'Applied',
  in_review: 'In Review',
  shortlisted: 'Shortlisted',
  interview: 'Interview',
  offer: 'Offer',
  hired: 'Hired',
  rejected: 'Rejected',
};

export const APPLICATION_STATUS_COLORS: Record<string, string> = {
  applied: 'bg-blue-100 text-blue-700',
  in_review: 'bg-yellow-100 text-yellow-700',
  shortlisted: 'bg-purple-100 text-purple-700',
  interview: 'bg-orange-100 text-orange-700',
  offer: 'bg-teal-100 text-teal-700',
  hired: 'bg-green-100 text-green-700',
  rejected: 'bg-red-100 text-red-700',
};

export const ROUTES = {
  home: '/',
  login: '/login',
  employerLogin: '/employer-login',
  register: '/register',
  userSignup: '/signup',
  employerSignup: '/employer-signup',
  verifyEmail: '/verify-email',
  oauthCallback: '/oauth/callback',
  oauthGoogleBridge: '/oauth/google-bridge',
  addEmail: '/add-email',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  // Applicant
  dashboard: '/dashboard',
  coding: '/coding',
  codingPractice: '/coding/practice',
  codingPracticeProblem: (problemVersionId: string) => `/coding/practice/${problemVersionId}`,
  codingAssessment: (sessionId: string) => `/coding/assessment/${sessionId}`,
  codingSubmissions: '/coding/submissions',
  codingSubmissionDetail: (id: string) => `/coding/submissions/${id}`,
  profile: '/profile',
  jobs: '/jobs',
  internships: '/internships',
  jobDetail: (id: string) => `/jobs/${id}`,
  applications: '/applications',
  interviewsHistory: '/interviews-history',
  savedJobs: '/saved-jobs',
  autoApply: '/auto-apply',
  credits: '/credits',
  interviews: '/interviews',
  notifications: '/notifications',
  referral: '/referral',
    community: '/community',
  messages: '/messages',
  roadmaps: '/roadmaps',
  roadmapDetail: (slug: string) => `/roadmaps/${slug}`,
  resumeDetail: (id: string) => `/resumes/${id}`,
  messageThread: (id: string) => `/messages/${id}`,
  resumeBuilder: '/resume-builder',
  autoApplySettings: '/auto-apply/settings',
  autoApplyQueueItem: (id: string) => `/auto-apply/queue/${id}`,
  coach: '/coach',
  // Recruiter
  recruiterDashboard: '/recruiter/dashboard',
  recruiterJobs: '/recruiter/jobs',
  recruiterNewJob: '/recruiter/jobs/new',
  recruiterJobDetail: (id: string) => `/recruiter/jobs/${id}`,
  recruiterJobApplications: (id: string) => `/recruiter/jobs/${id}/applications`,
  recruiterApplications: '/recruiter/applications',
  recruiterApplicationDetail: (id: string) => `/recruiter/applications/${id}`,
  recruiterMessages: '/recruiter/messages',
  recruiterAnalytics: '/recruiter/analytics',
  recruiterCredits: '/recruiter/credits',
  recruiterProfile: '/recruiter/profile',
  recruiterWebhooks: '/recruiter/settings/webhooks',
  recruiterIntegrations: '/recruiter/settings/integrations',
  recruiterAssessments: '/recruiter/assessments',
  recruiterAssessmentNew: '/recruiter/assessments/new',
  recruiterAssessmentDetail: (id: string) => `/recruiter/assessments/${id}`,
  recruiterAssessmentVersions: (id: string) => `/recruiter/assessments/${id}/versions`,
  recruiterAssessmentSubmissions: (versionId: string) => `/recruiter/assessments/versions/${versionId}/submissions`,
  recruiterSubmissionReview: (id: string) => `/recruiter/assessments/submissions/${id}`,
  recruiterProblems: '/recruiter/problems',
  recruiterProblemNew: '/recruiter/problems/new',
  recruiterProblemDetail: (id: string) => `/recruiter/problems/${id}`,
  recruiterCollections: '/recruiter/collections',
  recruiterBroadcasts: '/recruiter/broadcasts',
  // Admin
  adminDashboard: '/admin/dashboard',
  adminUsers: '/admin/users',
  adminJobs: '/admin/jobs',
  adminJobDetail: (id: string) => `/admin/jobs/${id}`,
  adminPostJob: '/admin/jobs/post',
  adminJobApprovals: '/admin/jobs/approvals',
  adminApplications: '/admin/applications',
  adminApplicationDetail: (id: string) => `/admin/applications/${id}`,
  adminMessages: '/admin/messages',
  adminCredits: '/admin/credits',
  adminActivity: '/admin/activity',
  // Developer / API
  apiKeys: '/settings/api-keys',
  apiDocs: '/docs',
};
